version : "3"
services:
  splade-web:
    build:
      context: .
      dockerfile: dockerfiles/Web.Dockerfile
    container_name: splade-web
    depends_on:
      - splade-pg
    volumes:
      - ./:/var/www/html
    restart: always
    ports:
      - "2114:80"
    environment:
      APP_NAME: 'Splade'
      XDEBUG_CONFIG: "mode=debug,coverage,develop client_host=host.docker.internal discover_client_host=1 start_with_request=yes"
    networks:
      splade-network:
        ipv4_address: 23.114.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  splade-pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    container_name: splade-pg
    volumes:
      - splade-pg-disk:/var/lib/postgres
    networks:
      splade-network:
        ipv4_address: 23.114.1.2

  splade-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: splade-mailpit
    restart: "no"
    networks:
      splade-network:
        ipv4_address: 23.114.1.4

  splade-fe:
    build:
      context: .
      dockerfile: dockerfiles/Fe.Dockerfile
    container_name: splade-fe
    depends_on:
      - splade-web
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    ports:
      - "2115:5173"
    networks:
      splade-network:
        ipv4_address: 23.114.1.6

# On-disk storage of DB data, when containers are stopped/removed
volumes:
  splade-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  splade-network:
    ipam:
      driver: default
      config:
        - subnet: 23.114.0.0/16
